# Data path. adjust them!
common:
    image_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.bmp"
    pcd_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.pcd"
    result_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1.43227869e+04, 0.0,   6.14833919e+02,
                0.0,     1.43247344e+04,   3.71244567e+02,
                0.0,     0.0,      1.0     ]
    dist_coeffs: [-7.23028676e-02, 4.40100998e+01, -3.54338418e-03, -6.84481883e-03, 1.40936880e-01]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/config/config_outdoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
