# Data path. adjust them!
common:
    image_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.bmp"
    pcd_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.pcd"
    result_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [1.64426762e+03, 0.00000000e+00, 7.11590519e+02,
                    0.00000000e+00, 1.64229914e+03, 5.72749385e+02,
                    0.00000000e+00, 0.00000000e+00, 1.00000000e+00]

    dist_coeffs: [-1.44783717e-01, 2.91541728e-01, -2.90344578e-04, 3.97609511e-04, -4.11407104e-01]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
