# Data path. adjust them!
common:
    image_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.bmp"
    pcd_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/input/0.pcd"
    result_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/result/extrinsic.txt"

# Camera Parameters. Adjust them!
camera:
    camera_matrix: [2.62486655e+03, 0.00000000e+00, 6.66897541e+02, 0.00000000e+00, 2.61964013e+03, 4.17765076e+02, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00]
    dist_coeffs: [-3.79878664e-01, 4.04140559e-01, 2.52991482e-04, 3.78890920e-04, -1.11638782e+00]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/alfayoung/Workspace/Calibration/src/livox_camera_calib/config/config_indoor.yaml"
    use_rough_calib: true # set true if your initial_extrinsic is bad
