%YAML:1.0

# Topic name in rosbag
PointCloudTopic: "/livox/lidar"
ImageTopic: "/camera/color/image_raw"

ExtrinsicMat: !!opencv-matrix
  rows: 4
  cols: 4
  dt: d
  data: [0.128205,-0.990314,0.0533056,0.166372,
         -0.0144147,-0.0556042,-0.998349,-0.047089,
         0.991643,0.127225,-0.0214038,-0.0771568,
         0,0,0,1]

  # data: [0.17364817766693033, -0.984807753012208, 0.0, 0,
  #        0.0, 0.0, -1.0, 0,
  #        0.984807753012208, 0.17364817766693033, 0.0, 0,
  #        0, 0, 0, 1]
# Params for Canny Edge Extraction

Canny.gray_threshold: 10
Canny.len_threshold: 200

# Params for Voxel Cutting & Plane Fitting & Edge Extraction
Voxel.size: 0.25
Voxel.down_sample_size: 0.02
Plane.min_points_size: 30
Plane.normal_theta_min: 60
Plane.normal_theta_max: 120
Plane.max_size: 8
Ransac.dis_threshold: 0.02
Ransac.iter_num: 200
Edge.min_dis_threshold: 0.05
Edge.max_dis_threshold: 0.1
